### ISSUE TITLE
`cabal-docspec` fails when using a custom GHC version (reloc bindist)

### ISSUE THREAD

**Issue by tbagrel1** [phadej/cabal-extras#160] opened 2024-10-07 15:54 UTC
I have a GHC version built from `master`, with command `hadrian/build --flavour=perf+late_ccs+ipe reloc-binary-dist-xz`

```bash
$ mydir/mycustomghc/bin/ghc --info

 [("Project name","The Glorious Glasgow Haskell Compilation System")
 ,("C compiler command","/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/cc")
 ,("C compiler flags","")
 ,("C++ compiler command","g++")
 ,("C++ compiler flags","")
 ,("C compiler link flags","-fuse-ld=gold -Wl,--no-as-needed")
 ,("C compiler supports -no-pie","YES")
 ,("CPP command","/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/cc")
 ,("CPP flags","-E")
 ,("Haskell CPP command","/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/cc")
 ,("Haskell CPP flags","-E -undef -traditional")
 ,("JavaScript CPP command","/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/cc")
 ,("JavaScript CPP flags","-E -CC -Wno-unicode -nostdinc")
 ,("C-- CPP command","/nix/store/gxpdysvlj9l6bfin03k6yq0s922pk7pg-gcc-wrapper-13.3.0/bin/cc")
 ,("C-- CPP flags","-E")
 ,("C-- CPP supports -g0","YES")
 ,("ld supports compact unwind","NO")
 ,("ld supports filelist","NO")
 ,("ld supports single module","NO")
 ,("ld is GNU ld","YES")
 ,("Merge objects command","ld.gold")
 ,("Merge objects flags","-r")
 ,("Merge objects supports response files","YES")
 ,("ar command","ar")
 ,("ar flags","q")
 ,("ar supports at file","YES")
 ,("ar supports -L","NO")
 ,("ranlib command","ranlib")
 ,("otool command","otool")
 ,("install_name_tool command","install_name_tool")
 ,("windres command","/bin/false")
 ,("unlit command","mydir/mycustomghc/lib/../bin/unlit")
 ,("cross compiling","NO")
 ,("target platform string","x86_64-unknown-linux")
 ,("target os","OSLinux")
 ,("target arch","ArchX86_64")
 ,("target word size","8")
 ,("target word big endian","NO")
 ,("target has GNU nonexec stack","YES")
 ,("target has .ident directive","YES")
 ,("target has subsections via symbols","NO")
 ,("target has libm","YES")
 ,("Unregisterised","NO")
 ,("LLVM target","x86_64-unknown-linux")
 ,("LLVM llc command","")
 ,("LLVM opt command","")
 ,("LLVM llvm-as command","")
 ,("Use inplace MinGW toolchain","NO")
 ,("Use interpreter","YES")
 ,("Support SMP","YES")
 ,("RTS ways","v thr thr_debug thr_debug_p thr_debug_p_dyn thr_debug_dyn thr_p thr_p_dyn thr_dyn debug debug_p debug_p_dyn debug_dyn p p_dyn dyn")
 ,("Tables next to code","YES")
 ,("Leading underscore","NO")
 ,("Use LibFFI","NO")
 ,("RTS expects libdw","NO")
 ,("Relative Global Package DB","package.conf.d")
 ,("Project version","9.11.20241002")
 ,("Project Git commit id","9e0b8445ba2ea9bc6d4af19a5c0d1148f39de4ba")
 ,("Project Version Int","911")
 ,("Project Patch Level","20241002")
 ,("Project Patch Level1","20241002")
 ,("Project Patch Level2","0")
 ,("Project Unit Id","ghc-9.11-inplace")
 ,("Booter version","9.6.6")
 ,("Stage","2")
 ,("Build platform","x86_64-unknown-linux")
 ,("Host platform","x86_64-unknown-linux")
 ,("Target platform","x86_64-unknown-linux")
 ,("Have interpreter","YES")
 ,("Object splitting supported","NO")
 ,("Have native code generator","YES")
 ,("target has RTS linker","YES")
 ,("Target default backend","native code generator")
 ,("Support dynamic-too","YES")
 ,("Support parallel --make","YES")
 ,("Support reexported-modules","YES")
 ,("Support thinning and renaming package flags","YES")
 ,("Support Backpack","YES")
 ,("Requires unified installed package IDs","YES")
 ,("Uses package keys","YES")
 ,("Uses unit IDs","YES")
 ,("GHC Dynamic","YES")
 ,("GHC Profiled","NO")
 ,("Debug on","NO")
 ,("LibDir","mydir/mycustomghc/lib")
 ,("Global Package DB","mydir/mycustomghc/lib/package.conf.d")
 ]
```

I cannot use `cabal-docspec` with it:

```bash
$ cabal-docspec -v -w mydir/mycustomghc/bin/ghc

[   0.00002] ghc.info: mydir/mycustomghc/bin/ghc
[   0.00073] process.0.start: cwd=/tmp mydir/mycustomghc/bin/ghc --info
[   0.08324] peu.die: ghc-9.11.20241002- is not prefix of Project Unit Id: ghc-9.11-inplace
```

I found the line responsible for this: https://github.com/phadej/cabal-extras/blob/68e436d06c0f00bcc2173c6536650d53c3953d07/peura/src/Peura/GHC.hs#L90-L95

I'm not sure to understand why we need this sanity check. I didn't set any custom unit ID or version name for my GHC build, so I expect `cabal-docspec` to work properly.

**Comment by phadej** [comment] 2024-10-07 19:43
`"Project Unit Id"` is used to by `cabal-install` to figure "abi tag" which is then used to created different package store directories. `Cabal` has following code:
 
 ```haskell
       compilerAbiTag :: AbiTag
      compilerAbiTag = maybe NoAbiTag AbiTag (Map.lookup "Project Unit Id" ghcInfoMap >>= stripPrefix (prettyShow compilerId <> "-"))
 ```
 
 And it silently deduces **no** abi tag for `"ghc-9.11-inplace"` project unit id AFAICT. I'd consider that a bug in either Cabal or GHC build system, that if fails to generate project unit id of the format as before.
 
 *Not generating an Abi Tag* defeats the whole purpose of the feature: to avoid similar versions with incompatible ABI to share the  cabal's package store. Arguably, `"ghc-9.11-inplace"` is not really a great abi tag.
 
 `cabal-docspec` takes cautious approach, and in case it cannot figure out abi tag, it fails (and doesn't silently continue like `Cabal`). and I won't change that until the issue is resolved in either GHC or Cabal. Report there.

**Comment by tbagrel1** [comment] 2024-10-08 08:49
Thanks for your fast reply, I just created https://gitlab.haskell.org/ghc/ghc/-/issues/25356

**Comment by mpickering** [comment] 2024-10-08 08:56
I think this is rather related to https://github.com/haskell/cabal/issues/10170

**Closed as completed** 2024-10-08 09:06 UTC
